### ISSUE TITLE
Xserver Bungee freez when disabling v2

### ISSUE THREAD

**Issue by przemek3697** [mickare/xserver#4] opened 2016-01-04 05:24 UTC
``
06:19:15 [INFO] [XServerProxy] --------- Proxy XServer ---------
06:19:15 [INFO] [XServerProxy] ----------  disabling  ----------
06:19:15 [WARNING] [XServerProxy] Exception while client connects: Socket closed
java.net.PlainSocketImpl.socketAccept(Native Method) (-2)
java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409) (409)
java.net.ServerSocket.implAccept(ServerSocket.java:545) (545)
java.net.ServerSocket.accept(ServerSocket.java:513) (513)
de.mickare.xserver.MainServer.run(MainServer.java:48) (48)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) (511)
java.util.concurrent.FutureTask.run(FutureTask.java:266) (266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) (1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) (617)
java.lang.Thread.run(Thread.java:745) (745)
``
Debian 8.2
On each disabling, bungeecord freez and don't respond.
I can repoduce this error.

**Comment by mickare** [comment] 2016-01-04 12:40
Thx for reporting przemek.

What BungeeCord version are you using?

**Comment by mickare** [comment] 2016-01-04 13:02
I changed some locks internally. Try the newest version 2.0.3!
http://nexus.spacier.de/content/repositories/rs-public/de/mickare/xserver/XServer-Bungee/2.0.3-SNAPSHOT/
Don't use version 3.0.0. It's still in development!

Could you describe how you reproduce this error?

**Comment by przemek3697** [comment] 2016-01-04 22:55
Yes, I only need to turn off BungeeCord, this bug is every time.
In a few hours i will try this build and I will give u some feedback

**Comment by przemek3697** [comment] 2016-01-05 05:27
Man, I don't know what you did in last commit but this is still this same as it was, but now without error after your log about disabling your plugin.

**Comment by mickare** [comment] 2016-01-05 12:49
I removed the error output for this particular exception, because the exception is normal when closing a socket while still waiting for a connection. It is not relevant.

Okay there is my second attempt.
I added a debug option to the config, just add ```debug: true``` to your config and it should log more information when disabling.

**Comment by mickare** [comment] 2016-01-05 15:12
I just broke the plugin and had to repair it (work of 2h). xX
Again I can't reproduce the bug. On my local machine with 4 bukkit and 2 bungeecords all servers stop normally.
Could you tell me at what point (with ```debug: true```) the plugin is freezing?

**Comment by przemek3697** [comment] 2016-01-07 06:00
```
06:18:28 [INFO] [XServerProxy] ---------------------------------
06:18:28 [INFO] [XServerProxy] --------- Proxy XServer ---------
06:18:28 [INFO] [XServerProxy] ----------  disabling  ----------
06:18:28 [INFO] [XServerProxy] Stopping XServerManager...
06:18:28 [INFO] [XServerProxy] Stopping MainServer...
06:18:28 [WARNING] [XServerProxy] Exception while client connects: Socket closed
java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
	at java.net.ServerSocket.implAccept(ServerSocket.java:530)
	at java.net.ServerSocket.accept(ServerSocket.java:498)
	at de.mickare.xserver.MainServer.run(MainServer.java:46)
	at de.mickare.xserver.MainServer$1.run(MainServer.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
06:18:28 [INFO] [XServerProxy] MainServer stopped
06:20:30 [INFO] [XServerProxy] Connection to SkyBlock1 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
06:20:30 [INFO] [XServerProxy] Disconnecting bungee4Test...
06:20:30 [INFO] [XServerProxy] Connection to skywars6 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
06:20:30 [INFO] [XServerProxy] bungee4Test disconnected
06:20:30 [INFO] [XServerProxy] Stopping XServerManager stopped
06:20:30 [INFO] [XServerProxy] XServerProxy disabled!
```

Look at times your plugin freeze bungee cord process for 2min, and after that bungee cord normally closed itself
`` Przekroczony czas oczekiwania na połączenie `` == `` time out  ``
Bungee freezing after message MainServer stopped. Information about Connection to XXX is showing always when bungeecord is frozen, and in the past I left frozen bungee and task with that message was working always, but bungee was still frozen today, as u can see bungeecord turn off after 2min. Its still not good for me because I don't know if this 2min is constant or this is random time or maybe one time "feathure" :smile:

**Comment by mickare** [comment] 2016-01-07 08:59
Thx, that helped a lot! :smile: 
Can you test again with the latest build?

**Comment by przemek3697** [comment] 2016-01-07 13:00
We have a problem, Java 8 :P In this changes u use Java 8, on my server is java 7. If you have the possibility to change this to Java 7 i can test this today, if u not, I don't know if i can test this ever

**Comment by przemek3697** [comment] 2016-01-07 13:12
Its looks like compilation bug, because i build this localy and now I can run this. I will test this

**Comment by przemek3697** [comment] 2016-01-07 14:07
Okay, its looks like it working but remember don't praise the day before the sunset.
I will check this one more time in the evening, and i will give u feedback about this :+1: 
If u can please fix only this ``java.lang.UnsupportedClassVersionError: de/mickare/xserver/BungeeXServerPlugin : Unsupported major.minor version 52.0
``

**Comment by mickare** [comment] 2016-01-07 14:47
```Unsupported major.minor version 52.0``` seems not to be from me. Did you add your runtimes to your maven ```...\.m2\settings.xml``` file? (https://gist.github.com/mickare/1b9d036fd595a4e41910)

I recompiled & uploaded it.

**Comment by przemek3697** [comment] 2016-01-08 03:47
```
04:36:31 [INFO] [XServerProxy] ---------------------------------
04:36:31 [INFO] [XServerProxy] --------- Proxy XServer ---------
04:36:31 [INFO] [XServerProxy] ----------  disabling  ----------
04:36:31 [INFO] [XServerProxy] Stopping XServerManager...
04:36:31 [INFO] [XServerProxy] Stopping MainServer...
04:36:31 [INFO] [XServerProxy] Disconnecting Hub6...
04:36:31 [WARNING] [XServerProxy] Exception while client connects: Socket closed
java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
	at java.net.ServerSocket.implAccept(ServerSocket.java:530)
	at java.net.ServerSocket.accept(ServerSocket.java:498)
	at de.mickare.xserver.MainServer.run(MainServer.java:57)
	at de.mickare.xserver.MainServer$1.run(MainServer.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
04:36:31 [INFO] [XServerProxy] Hub6 disconnected
04:36:31 [INFO] [XServerProxy] MainServer stopped
04:38:33 [INFO] [XServerProxy] Disconnecting Hub7...
04:38:33 [INFO] [XServerProxy] Connection to anni2 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
04:38:33 [INFO] [XServerProxy] Connection to skywars6 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
04:38:33 [INFO] [XServerProxy] Hub7 disconnected
04:38:33 [INFO] [XServerProxy] Disconnecting Hub8...
04:38:33 [INFO] [XServerProxy] Connection to anni3 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
04:38:33 [INFO] [XServerProxy] Connection to anni1 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
04:38:33 [INFO] [XServerProxy] Hub8 disconnected
04:38:33 [INFO] [XServerProxy] Connection to anni4 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
04:38:33 [INFO] [XServerProxy] Disconnecting Hub1...
04:38:33 [INFO] [XServerProxy] Connection to SkyBlock1 failed! {Cause: Przekroczony czas oczekiwania na połączenie}
04:38:33 [INFO] [XServerProxy] Hub1 disconnected
04:38:33 [INFO] [XServerProxy] Disconnecting bungee1...
04:38:33 [INFO] [XServerProxy] bungee1 disconnected
04:38:33 [INFO] [XServerProxy] XServerManager stopped
04:38:33 [INFO] [XServerProxy] XServerProxy disabled!
```
For clarity, all the time I using yours builds.
Now u can see this same error after ``[XServerProxy] MainServer stopped``. (look at time)
Please add more debug after that message

**Comment by mickare** [comment] 2016-01-08 05:05
Wow writing "fix ..." in the commit message automatically closes the issue.
I added more debug information in the critical part. Could you try again? ^^
This is hard, because I can't reproduce and ergo can't test it.

**Comment by przemek3697** [comment] 2016-01-10 05:55
Hmm its looks like working. I can't reproduce this error. U change closing connections to servers (sockets) and now all its good. I think :P I think we are fix this. If u can please leave all debug info maybe for next time (I hope no)

**Comment by mickare** [comment] 2016-01-10 21:44
Yep I'll leave the debug option. But in default it is disabled.

**Closed by mickare** 2016-01-10 21:44 UTC
